### ISSUE TITLE
Add support for 'browsers' option

### ISSUE THREAD

**Issue by jeluard** [danielsz/boot-autoprefixer#1]
Autoprefixer has a pretty nice `browsers` option allowing to define what subset of browsers you want to support. It would be great to be able to specify it.

**Comment by danielsz** [comment]
Absolutely. Would you like to try a hand at it? I'll be happy to take a PR.

**Comment by jeluard** [comment]
Sure! See #2.

**Comment by danielsz** [comment]
Merged. Thank you, @jeluard.
