### ISSUE TITLE
Problems with latest postcss-cli

### ISSUE THREAD

**Issue by adstage-david** [danielsz/boot-autoprefixer#9]
Been tracing a build error I got this morning after merging in changes from our designer to add boot-autoprefixer. Looks like a new version of postcss-cli is out and requires a slight change in how files are referenced:

https://github.com/postcss/postcss-cli/issues/89

You end up with an error that looks like:

```
PluginError: Cannot find module '/home/david/.boot/cache/tmp/media/projects/report-center/fwy/6qp7pj/app.css'
```

Because the latest version interprets the arguments differently and treats your CSS as a plugin.

**Comment by danielsz** [comment]
Thank you, @adstage-david 

Are you in the mood for a PR? :-)

**Comment by adstage-david** [comment]
I could probably do that - do you want to support the beta version right now, or is the fix just to reference the specific version to install in the README (`npm install -g postcss-cli@2.6.0`) to keep it from tripping up anyone until the next stable version comes out?

**Comment by danielsz** [comment]
Would it be possible to autodetect the version used and determine the shell command consequently?

**Comment by adstage-david** [comment]
Turns out there's a syntax that works for both, so I PR'd with that.

**Comment by danielsz** [comment]
Oh, that's handy. Thank you. I'll review asap.
